version: '3'

services:
  db:
    container_name: Carga_academica_db
    image: postgres
    ports:
      - "5532:5432"
    env_file:
      - .env
    #volumes: 
    #  - carga_db:/var/lib/postgresql/data/pgdata
  web:  
    container_name: Carga_academica
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  carga_db:
    external: true