# Generated by Django 2.2 on 2021-10-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evado', '0002_auto_20211018_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='personauniversoencuesta',
            name='encuesta_finalizada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='periodoencuesta',
            name='anio',
            field=models.PositiveIntegerField(default=2021, verbose_name='Año'),
        ),
    ]
