# Generated by Django 2.2 on 2021-10-28 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0002_auto_20211028_1547'),
        ('evado', '0003_auto_20211020_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalaDesempeno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Escala de desempeño',
                'verbose_name_plural': 'Escalas de desempeño',
            },
        ),
        migrations.CreateModel(
            name='EscalaValoracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspecto', models.CharField(max_length=100, verbose_name='Aspecto a valorar')),
                ('min', models.PositiveIntegerField(verbose_name='Valor mínimo')),
                ('max', models.PositiveIntegerField(verbose_name='Valor máximo')),
            ],
            options={
                'verbose_name': 'Escala de valoración',
                'verbose_name_plural': 'Escalas de valoración',
            },
        ),
        migrations.CreateModel(
            name='ResultadoPersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Nota final')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Persona')),
                ('universo_encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evado.UniversoEncuesta')),
            ],
            options={
                'verbose_name': 'Resultado de encuesta de persona',
                'verbose_name_plural': 'Resultados de encuestas de personas',
            },
        ),
        migrations.AddField(
            model_name='encuesta',
            name='indice_confiabilidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Índice de confiabilidad'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.CreateModel(
            name='ResultadoPreguntaPersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio_autoevaluacion', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Promedio de autoevaluación')),
                ('peso_autoevaluacion', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Peso de autoevaluación')),
                ('promedio_pares', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Promedio de pares')),
                ('peso_pares', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Promedio de pares')),
                ('promedio_directivos', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Promedio de directivos')),
                ('peso_directivos', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Promedio de directivos')),
                ('nota', models.DecimalField(decimal_places=1, max_digits=2)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evado.PreguntaEncuesta')),
                ('resultado_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evado.ResultadoPersona')),
            ],
            options={
                'verbose_name': 'Resultado de pregunta de persona',
                'verbose_name_plural': 'Resultados de preguntas de personas',
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=100, verbose_name='Nivel de desempeño')),
                ('min', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Valor mínimo')),
                ('max', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Valor máximo')),
                ('escala_desempeno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evado.EscalaDesempeno', verbose_name='Escala de desempeño')),
            ],
            options={
                'verbose_name': 'Nivel de desempeño',
                'verbose_name_plural': 'Niveles de desempeño',
            },
        ),
        migrations.AddField(
            model_name='encuesta',
            name='escala_valoracion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evado.EscalaValoracion', verbose_name='Escala de valoración'),
        ),
        migrations.AddField(
            model_name='universoencuesta',
            name='escala_desempeno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evado.EscalaDesempeno', verbose_name='Escala de desempeño'),
        ),
        migrations.CreateModel(
            name='Ponderacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ponderacion', models.PositiveIntegerField(verbose_name='Ponderación')),
                ('tipo_encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evado.TipoUniversoEncuesta', verbose_name='Tipo de encuesta')),
                ('universo_encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evado.UniversoEncuesta', verbose_name='Universo de encuestas')),
            ],
            options={
                'verbose_name': 'Ponderación',
                'verbose_name_plural': 'Ponderaciones',
                'unique_together': {('universo_encuesta', 'tipo_encuesta')},
            },
        ),
    ]
