# Generated by Django 2.2 on 2021-10-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evado', '0004_auto_20211028_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadopersona',
            name='nota',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Nota final'),
        ),
    ]
