# Generated by Django 2.2 on 2021-11-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evado', '0005_auto_20211028_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadopreguntapersona',
            name='nota',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
