# Generated by Django 2.2 on 2021-10-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecolegio',
            name='tipo_subvencion',
            field=models.CharField(choices=[('gratuito', 'Gratuito'), ('particular_subvencionado', 'Particular Subvencionado'), ('particular', 'Particular')], default='particular_subvencionado', max_length=75, verbose_name='Tipo de subvención'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='solo_lectura',
            field=models.BooleanField(default=False, help_text='Marque si el perfil que está creando, será solo para lectura'),
        ),
    ]
