version: "3"

services:
  db:
    container_name: aagesuite_db
    image: postgres
    restart: always
    ports:
      - "5532:5432"
    env_file: .env
    volumes:
      - db:/var/lib/postgresql/data

  web:
    container_name: aagesuite
    restart: always
    image: registry-gitlab.unach.cl/aage/aagesuite:test
    env_file: .env
    command: ./start.sh
    volumes:
      - /srv/webapps/aagesuite/media:/webapp/media
      - /srv/webapps/aagesuite/static:/webapp/static
      - /srv/webapps/aagesuite/logs:/webapp/logs
    ports:
      - "8001:8000"
    tty: true
    depends_on:
      - db

volumes:
  db:
